name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:

  build:
    name: build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ['3.10']
        architecture: ['x64']

    steps:
      - uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: packages
        if: matrix.os == 'ubuntu-latest'
        run: apt-get update && apt-get install -y libsdl2-dev

      - name: requirements
        run: python -m pip install -U pip wheel setuptools requests

      - name: deps
        run: python deps.py

      - name: wheel
        run: python setup.py bdist_wheel
