name: release

on:
  workflow_dispatch:

jobs:

  sdist:
    name: Package source
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: x64

      - name: requirements
        run: python -m pip install -U pip wheel setuptools requests

      - name: deps
        run: python deps.py

      - name: sdist
        run: python setup.py sdist -d package

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: package/*.tar.gz

  wheels:
    name: Build wheels
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: requirements
        run: python -m pip install -U pip wheel setuptools requests cibuildwheel==2.9.0

      - name: deps
        run: python deps.py

      - name: wheels
        run: python -m cibuildwheel --output-dir package
        env:
          CIBW_BUILD: cp39-win_amd64 cp310-win_amd64

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: package/*.whl
